# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 69e84aab54e126e8494b38892b41ca4d13bb79357217ad508fb1ddb97a3cefbad8912b044b32c9e49ccd983f45bb23437014e7ddaed14e0a99301a485acfb303

test:
  secret_key_base: 9eb2ce7d4df675d6c42b8dc98843df0a5b4cd6ff768e24f8aa54c266096f0a8d2c0a2df4fbfadcf6af1dc1ca65b157bb387946e84e33f1b69de185f747f0f516

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
